### ISSUE TITLE
QtPy vs PyQt5 in autogenerated files

### ISSUE THREAD

**Issue by goanpeca** [fcaprile/PyFocus#7]
Hi team!

While working on https://github.com/conda-forge/pycustomfocus-feedstock/pull/5 we noticed some files are directly importing pyqt5

See: https://github.com/search?q=repo%3Afcaprile%2FPyFocus%20pyqt5&type=code

These are autogenerated files, but imply a forced dependency on pyqt5

The plugin documentation for napari has a set of best practices for developers, which includes a clause recommending not to depend directly on PyQt5 or PySide2 to allow end-users to choose their bindings freely. [More details here](https://napari.org/stable/plugins/best_practices.html#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies).

The files using `PyQt5` instead of `qtpy` are listed here -> https://github.com/bauerdavid/napari-nD-annotator/search?q=pyqt5

We made a [patch over at conda forge](https://github.com/conda-forge/pycustomfocus-feedstock/pull/5/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aL12) to replace pyqt5 by qtpy 

Is there a reason you need PyQt5 explicitly? Could these imports be updated to use `qtpy` for the next release and add some instructions so that this is manually fixed whenever the UI is regenrated?

Thanks and cheers 🚀 !

**Comment by fcaprile** [comment]
Hi! 
PyQt5 is the library that was used for the standalone PyFocus UI that is not implemented by napari. 

Since this library is not used with napari, if the installation of PyQT5 does not generate any problems I would preffer to keep it to mantain the legacy functions of PyFocus before it was meant to be used with napari.

**Comment by goanpeca** [comment]
Hi @fcaprile, this library is used by napari plugins so indirectly it would lead to installations bringing pyqt5. On conda forge we removed the pyqt5 dependency and patched the files to achieve this goal, but I understand you would prefer to leave it as is.

Cheers

**Comment by fcaprile** [comment]
Ok, if it leads to problems then I will see to remove it for a next release. 

Cheers.

**Comment by fcaprile** [comment]
Removed pyqt5 from requirements
